#ifndef COMMON_H
#define COMMON_H

#include <windows.h>

namespace emu {

/**
 * @brief Used to mark parameter as unused.
 */
#define UNUSED_PARAMETER(name)

/**
 * @brief References specified variable or parameter as dummy value.
 *
 * Used to suppress unreferenced parameter/variable warning if variable
 * is used in way which can not be detected by the compiler (asm) on in debug
 * mode only.
 */
#define REFERENCE(name) name;

#pragma warning (disable:4512) // assignment operator could not be generated
#pragma warning (disable:4127) // conditional expression is constant - generated by check in the logKA() macro.

} // namespace emu

#endif // COMMON_H

// EOF //
