#ifndef DDRAW7_EMU_H
#define DDRAW7_EMU_H

#include "../helpers/interface.h"
#include "../helpers/log.h"
#include "ddraw.h"
#include <list>

namespace emu {

class DirectDraw7Emu : public IUnknownImpl, public IDirectDraw7 {

public:

    // IUnknown.

    IUNKNOWN_IMPLEMENTATION()
    GET_IMPLEMENTATION_BEGIN()
    GET_IMPLEMENTATION_IFACE(IID_IDirectDraw7, IDirectDraw7)
    GET_IMPLEMENTATION_END()

    //  IDirectDraw7 methods

    STDMETHODIMP Compact() UNSUPPORTED;
    STDMETHODIMP CreateClipper(DWORD, LPDIRECTDRAWCLIPPER FAR*, IUnknown FAR *) UNIMPLEMENTED;
    STDMETHODIMP CreatePalette(DWORD, LPPALETTEENTRY, LPDIRECTDRAWPALETTE FAR*, IUnknown FAR *) UNIMPLEMENTED;

    STDMETHODIMP CreateSurface(LPDDSURFACEDESC2, LPDIRECTDRAWSURFACE7 FAR *, IUnknown FAR *) UNIMPLEMENTED;
    STDMETHODIMP DuplicateSurface(LPDIRECTDRAWSURFACE7, LPDIRECTDRAWSURFACE7 FAR *) UNIMPLEMENTED;
    STDMETHODIMP EnumDisplayModes(DWORD, LPDDSURFACEDESC2, LPVOID, LPDDENUMMODESCALLBACK2) UNIMPLEMENTED;
    STDMETHODIMP EnumSurfaces(DWORD, LPDDSURFACEDESC2, LPVOID,LPDDENUMSURFACESCALLBACK7) UNIMPLEMENTED;
    STDMETHODIMP FlipToGDISurface() UNIMPLEMENTED;
    STDMETHODIMP GetCaps(DDCAPS *, DDCAPS *) UNIMPLEMENTED;
    STDMETHODIMP GetDisplayMode(LPDDSURFACEDESC2) UNIMPLEMENTED;
    STDMETHODIMP GetFourCCCodes(LPDWORD, LPDWORD) UNIMPLEMENTED;
    STDMETHODIMP GetGDISurface(LPDIRECTDRAWSURFACE7 FAR *) UNIMPLEMENTED;
    STDMETHODIMP GetMonitorFrequency(LPDWORD) UNSUPPORTED;
    STDMETHODIMP GetScanLine(LPDWORD) UNIMPLEMENTED;
    STDMETHODIMP GetVerticalBlankStatus(LPBOOL) UNIMPLEMENTED;
    STDMETHODIMP Initialize(GUID FAR *) UNIMPLEMENTED;
    STDMETHODIMP RestoreDisplayMode() UNIMPLEMENTED;
    STDMETHODIMP SetCooperativeLevel(HWND, DWORD) UNIMPLEMENTED;
    STDMETHODIMP SetDisplayMode(THIS_ DWORD, DWORD,DWORD, DWORD, DWORD) UNIMPLEMENTED;
    STDMETHODIMP WaitForVerticalBlank(DWORD, HANDLE) UNIMPLEMENTED;
    STDMETHODIMP GetAvailableVidMem(LPDDSCAPS2, LPDWORD, LPDWORD) UNIMPLEMENTED;
    STDMETHODIMP GetSurfaceFromDC(HDC, LPDIRECTDRAWSURFACE7 *) UNIMPLEMENTED;
    STDMETHODIMP RestoreAllSurfaces(void) UNIMPLEMENTED;
    STDMETHODIMP TestCooperativeLevel(void) UNIMPLEMENTED;
    STDMETHODIMP GetDeviceIdentifier(LPDDDEVICEIDENTIFIER2, DWORD ) UNIMPLEMENTED;
    STDMETHODIMP StartModeTest(LPSIZE, DWORD, DWORD ) UNIMPLEMENTED;
    STDMETHODIMP EvaluateMode(DWORD, DWORD * ) UNIMPLEMENTED;

};

} // namespace emu

#endif // DDRAW_EMU_H

// EOF //
